### ISSUE TITLE
`execution-status-count` doesn't seem to work with tasks in sub-workflows

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/cromshell#112]
It seems to only display results from level 1 tasks.
So if any of the level 1 tasks is actually a sub-workflow, it won't display the results from the tasks in that sub-workflow.

**Comment by SHuang-Broad** [comment]
It turns out that one needs to supply the sub-workflow ID to see results in either `execution-status-count` or the `timing` page.

**Comment by kvg** [comment]
But it would still be nice to be able to see this without having to look up the sub-workflow ID.  Right now I have to do this in three steps:

1. What's the status of my workflow?
```
> cromshell execution-status-count -p -x fd57b6df-a62a-4d20-9f6d-19bce75e2536                                                              
Sub-Command: execution-status-count
Using workflow-id == fd57b6df-a62a-4d20-9f6d-19bce75e2536
Using workflow server URL == https://cromwell-v47.dsde-methods.broadinstitute.org
fd57b6df-a62a-4d20-9f6d-19bce75e2536	Running
	ONT10xSingleFlowcell.FindSequencingSummaryFiles	0 Running, 1 Done, 0 Preempted 0 Failed
	ONT10xSingleFlowcell.GetRunInfo	0 Running, 2 Done, 0 Preempted 0 Failed
	ONT10xSingleFlowcell.ListFastqs	0 Running, 2 Done, 0 Preempted 0 Failed
	ONT10xSingleFlowcell.PartitionFastqManifest	0 Running, 2 Done, 0 Preempted 0 Failed
	ScatterAt52_18	2 Running, 0 Done, 0 Preempted 0 Failed
```

2. What's the workflow ID of what the scatter is running?
```
> cromshell metadata fd57b6df-a62a-4d20-9f6d-19bce75e2536 2> /dev/null | grep 'call-ScatterAt52_18' | grep -m1 stdout
                        "stdout": "gs://broad-dsde-methods-long-reads-intermediate/ONT10xSingleFlowcell/fd57b6df-a62a-4d20-9f6d-19bce75e2536/call-ScatterAt52_18/shard-0/ScatterAt52_18/8722c3e6-1cb1-4884-8f0b-bdb32c9d6221/call-C3POa/shard-0/C3POa/ff289e11-5a7b-47ff-bcdc-cb737c8c374b/call-Preprocessing/stdout",
```

3. What's the status of that scattered sub-workflow?
```
> cromshell execution-status-count -p -x 8722c3e6-1cb1-4884-8f0b-bdb32c9d6221                                                              
Sub-Command: execution-status-count
Using workflow-id == 8722c3e6-1cb1-4884-8f0b-bdb32c9d6221
Using workflow server URL == https://cromwell-v47.dsde-methods.broadinstitute.org
8722c3e6-1cb1-4884-8f0b-bdb32c9d6221	Running
	ONT10xSingleFlowcell.AnnotateAdapters	2 Running, 0 Done, 1 Preempted 0 Failed
	ONT10xSingleFlowcell.C3POa	48 Running, 2 Done, 0 Preempted 0 Failed
```

Can execution-status-count be made to expand to this level?

**Comment by lbergelson** [comment]
It seems like cromwell changed how subworkflows were specified in a recent version which once again broke subworkflow expansion.  We can try to fix it.  Is there a cromwell endpoint to list all the subworkflows for a job?

**Comment by lbergelson** [comment]
@kvg What cromwell server are you running against?

**Comment by SHuang-Broad** [comment]
It doesn't work with methods 47. @lbergelson

**Comment by SHuang-Broad** [comment]
Not sure if [this](https://github.com/broadinstitute/cromshell/blob/17738602b5f8b2c9a78f9b4c65d3d37af691b862/cromshell#L966) is the line to investigate.
