### ISSUE TITLE
execution-status-count does not seem to support alias

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/cromshell#118]

**Comment by lbergelson** [comment]
it also is broken for alias

**Comment by SHuang-Broad** [comment]
Someday, we need to do a refactoring.
I feel like the functionality is growing much bigger than the original design.
It's great many people are using cromshell (and let's make sure we don't become like Robinhood :joy_cat:)

**Comment by lbergelson** [comment]
Yeah, we need to rewrite in a sane language, but it's some work and no one really has time.
