### ISSUE TITLE
Strange behavior, every other submission fails

### ISSUE THREAD

**Issue by fleharty** [broadinstitute/cromshell#132]
Any idea what's going on here?

<img width="773" alt="Screenshot 2020-06-23 15 29 39" src="https://user-images.githubusercontent.com/10714381/85450413-bb300700-b566-11ea-8b2e-c05a20973a75.png">

**Comment by lbergelson** [comment]
It's the ancient turtle dance of death!

**Comment by lbergelson** [comment]
I have no idea what's going on... Spotty connection to cromwell is my guess but the weird periodicity is suspect.

**Comment by jonn-smith** [comment]
Looks like a slow server / connection issue.

**Comment by fleharty** [comment]
@jonn-smith I think you're right.  The periodicity is what made me think it wasn't a connection.  But I have continued to run into this problem, but it is no longer periodic.  I think the bizarre behavior I saw was by chance.
