### ISSUE TITLE
Resume a job

### ISSUE THREAD

**Issue by boboppie** [broadinstitute/cromshell#138]
Dear cromshell developers,

Thank you for creating and sharing cromshell to the community.

I have a job which was failed in the middle of the run due to a missing reference file. Is there a way to resume the job after the missing file is in place? At the moment I have to submit a new job which takes a long time to run to where it was broken.

Best wishes,
Fengyuan

**Comment by jonn-smith** [comment]
Hi @boboppie 
This is really more of a [Cromwell](https://github.com/broadinstitute/cromwell) question.  Cromshell is a CLI for Cromwell (which actually runs the jobs you submit).  

That said, if your Cromwell instance supports call caching then you should be able to resubmit a job and only the parts that did not  run correctly will be run (assuming all the inputs are the same for the other jobs).  If you change the inputs to your main workflow then this may not work though.  You can look up call caching in the Cromwell documentation for more information, or contact the Cromwell team for direct support.
