### ISSUE TITLE
Timing URL is missing a colon

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/cromshell#167]
I just installed the latest cromshell via `brew install broadinstitute/dsp/cromshell`.

When I run `cromshell timing` my browser (Chromw) tries to a URL that looks like this:

`https//~{SERVER}/api/workflows/v1/${WORKFLOW_ID}/timing`

Which is missing the colon after the `https`. The link works if I manually add a colon in.

**Comment by lbergelson** [comment]
Woops.  Thanks for noticing.
