### ISSUE TITLE
submit command could go one step further

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/cromshell#193]
Making the dependency zip for the user.

Who hasn't been bitten by their own mistakes from forgetting to remake the zip after changing the imported WDLs?

**Comment by lbergelson** [comment]
That sounds like a great idea.  Add a dependency folder instead and it will zip it for you?

**Comment by SHuang-Broad** [comment]
yes, that could solve the problem.

**Comment by jonn-smith** [comment]
I had figured it would zip up the parent directory of the specified WDL.  That way no other inputs were required (except a flag).  

In practice I've found that this will solve all of my use cases at least.

**Comment by microbioticajon** [comment]
I think allowing the user to explicitly specify a dependency directory would be my preference.

Although, admittedly, I have probably have a slightly odd setup...

My projects often look like this:
```
bobs_pipeline
  |__ tasks
  |__ workflows
    |__ sub_workflow.wdl
    |__ main_workflow.wdl
entrypoints
  |__ main_workflow_entrypoint.wdl
package.json (defines libraries I want to import from other projects into my zip)
```
The bobs_pipeline directory is the lib that forms a reusable library and is zipped while the entrypoint.wdl is what the user interacts with (its a simple lightweight wrapper around main_workflow.wdl) and sits outside the zip. The advantage here is that when I deploy I have a clear separation of the workflows Im expected to run and their dependencies.

Tangentially, I use this pattern in conjunction with NPM to manage the tree of dependences (i.e. multiple versioned libraries from other projects) - bobs_pipeline can be imported by another library and, using NPM (plus a simple helper script), Im able to build complicated, versioned dependency zips for sets of pipelines and provide entrypoints into them. All the user/automation system has to do is clone the project repo and run `npm run build:wdl-zip` to generate a ./dist/dependencies.wdl.zip.

Its possibly overly convoluted but seems to work well enough...

**Comment by bshifaw** [comment]
Added to cromshell2 as kshakir mentioned

**Comment by SHuang-Broad** [comment]
@bshifaw then #230 Readme probably need to be updated to reflect this awesome new feature.
