### ISSUE TITLE
FR: Cromshell support for no-turtle mode

### ISSUE THREAD

**Issue by mbookman** [broadinstitute/cromshell#225]
The Cromshell turtle is very cute, both turtle() and turtleDead().

However, the turtle does end up consuming valuable vertical real-estate on a user's screen. It would be nice to have a flag or environment variable to pass which suppresses the turtle.

Will put out the specific suggestion of a `--compact-output` flag. Other tools often have a `--silent` or `--quiet` option. For example `gcloud` has a --quiet option:

https://cloud.google.com/sdk/gcloud/reference

> --quiet, -q
>
> Disable all interactive prompts when running gcloud commands. If input is required, defaults will be used, or an error will be raised.

which is a little different. gsutil has 

https://cloud.google.com/storage/docs/gsutil/addlhelp/GlobalCommandLineOptions

> -q
>
> Causes gsutil to perform operations quietly, i.e., without reporting progress indicators of files being copied or removed, etc. > Errors are still reported. This option can be useful for running gsutil from a cron job that logs its output to a file, for which the only information desired in the log is failures.

which is also a little bit different.

gcloud also has the verbosity flag:

> --verbosity=VERBOSITY; default="warning"
>
> Override the default verbosity for this command. Overrides the default core/verbosity property value for this command invocation. VERBOSITY must be one of: debug, info, warning, error, critical, none.

which might be one to follow. Cromshell could have (at the moment):

> --verbosity=VERBOSITY; default="normal"
>
> Override the default verbosity for this command. Options are "normal, quiet, silent"

where "quiet" suppresses the turtles and silent suppresses anything non-essential.

I'm mostly interested in the "quiet" option; not sure if "silent" is really of value, so adding that could certainly be deferred.

**Comment by jonn-smith** [comment]
I like the idea of a `-q` flag.  This may already be implemented in `cromshell 2.0` - I remember talking about it as a feature.

@bshifaw - is this part of the feature set?

**Comment by bshifaw** [comment]
yes, its implemented with `--hide_logo`

**Comment by SHuang-Broad** [comment]
@bshifaw this can be closed, right?
