### ISSUE TITLE
bioconda recipe

### ISSUE THREAD

**Issue by notestaff** [broadinstitute/cromshell#39]
Thanks for cromshell.  I added a bioconda recipe for it -- maybe mention in the docs it's installable through bioconda.  @lbergelson

**Comment by lbergelson** [comment]
@notestaff Neat!  Thanks for adding that!  I've never used bioconda, could you provide the command you'd use to install it?  ex `bioconda install cromshell` or whatever the appropriate bit is?

**Comment by notestaff** [comment]
First install bioconda (instructions at https://bioconda.github.io/ ) , then do 
conda install cromshell
This will also install cromwell and jq , if needed.

**Comment by lbergelson** [comment]
Thank you for adding the recipe!  It's great to see people using it.

**Comment by lbergelson** [comment]
I added a note to the readme #40 .
