### ISSUE TITLE
Submit action should allow waiting for task to change from `submitted` to some final/running state.

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/cromshell#49]
We need to add a `-w` flag that will wait for the task submitted by the user to go from the `Submitted` state to some other state.

**Comment by lbergelson** [comment]
Is the idea here to have cromshell wait and poll until it switches to `Running` or `Failed` before it returns?

The need for this sounds similar to my thought to do local validation before submitting #18

**Comment by jonn-smith** [comment]
Yeah, exactly. 

It's pretty straightforward / simple, and I find myself doing this on the command-line every time I submit a job so it should probably be automated.

**Comment by lbergelson** [comment]
It's a good idea.

**Comment by jonn-smith** [comment]
It's similar to #18, but will catch things that are not technically invalid on the WDL side.

**Comment by lbergelson** [comment]
Yeah, it's still valuable even if we did local validation.

**Comment by lbergelson** [comment]
I think most of the immediate failures could be preempted though if we did local validation.

**Comment by jonn-smith** [comment]
Oh absolutely.  This would be in addition.
