### ISSUE TITLE
Print "Sub-Command: ${SUB_COMMAND}" to stderr?

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/cromshell#60]
I'm talking about this line

https://github.com/broadinstitute/cromshell/blob/69d18ba5a421d74e2d07dc86f6f1a0328f97469e/cromshell#L1462

Reason:
while I was doing `cromshell metadata ${my_id} > ${my_id}.metadata.json`, the JSON is invalid due to that line.

Not sure if people have objections.

**Comment by lbergelson** [comment]
Good call, will change.
