### ISSUE TITLE
conda installs outdated version of womtool

### ISSUE THREAD

**Issue by mwalker174** [broadinstitute/cromshell#93]
Installation of cromshell with `conda` causes all submissions of WDL 1.0 scripts to fail. This is because the distribution of `cromwell` installed as a dependency is outdated.

**Comment by mwalker174** [comment]
@jonn-smith Whoops, I meant conda

**Comment by jonn-smith** [comment]
@mwalker174 We don't actually control the conda environment... someone else put in the recipe / build for us.  

Neither @lbergelson nor I know who it is, so we don't know who to poke to update it.

**Comment by lbergelson** [comment]
@mwalker174 It looks like there is a dependency on cromwell in the bioconda recipe.  What version of cromwell is it installing for you?  Cromwell should include the matching womtool but it might not or you might have an out of date one.  I'm going to submit a patch to change the dependency from cromwell -> womtool which is a weaker requirement.

**Comment by lbergelson** [comment]
I opened a pr to change the dependency from cromwell -> womtool which might help? https://github.com/bioconda/bioconda-recipes/pull/17160

**Comment by lbergelson** [comment]
@mwalker174 Did this fix it?

**Comment by mwalker174** [comment]
@lbergelson Yes sorry I somehow missed your comments. I was able to run a WDL 1.0 workflow installing with conda just now.
