### ISSUE TITLE
Timing result seemingly off for methods server 47

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/cromshell#99]
Example is

```
https://cromwell-v47.dsde-methods.broadinstitute.org/api/workflows/v1/2c14a767-176e-458a-a32b-43fe494ace17/timing
```

which shows computing time less than the actual computing time, e.g. [here](gs://broad-methods-cromwell-exec-bucket-v47/TrioBinChildLongReads/2c14a767-176e-458a-a32b-43fe494ace17/call-ParentalReadsRepartition/ParentalReadsRepartition.log).

The UI is also not showing localization/delocalization time either.

Not sure if it is an issue of cromshell or something else.

**Comment by lbergelson** [comment]
@SHuang-Broad Cromshell timing just links to the cromwell timing page, so any bug there is a cromwell issue, not cromshell.  I recommend reporting it to the cromwell team.
